### ISSUE TITLE
[Git] No Carrion drops?

### ISSUE THREAD

**Issue by Techokami** [MajorCooke/Doom4Doom#1]
I just downloaded the Git repos for the mod and resources (mod repo commit 0fe161e, resource repo commit d98e1f5), crunched them into a PK3, and started playing on GZDoom 2.3.0, only to find that when I gibbed enemies, they didn't drop Carrion anymore like they did in the 2.0.3 release of the mod.

????????????????

**Comment by MajorCooke** [comment]
Fixed.

**Comment by Techokami** [comment]
Cheers~!
