### ISSUE TITLE
[Git] Can't unmorph with weapon mod key?

### ISSUE THREAD

**Issue by Techokami** [MajorCooke/Doom4Doom#10]
Doom4Doom commit 8dcdb5c, Doom4DoomResources commit 300c9a2, GZDoom 2.4pre-127-g386c00f
When you collect a Demon Rune, it was possible to cancel the morph by pressing the weapon mod key. Except that doesn't work anymore and you have to wait out the timer instead...?

**Comment by MajorCooke** [comment]
There's a new keybind for it specifically.

**Comment by Techokami** [comment]
Aha! Thanks for that. I wasn't aware of this change. (I was going to report the janky teleporting ledge grabbing, but I saw in the commits that it's deliberate until a new system is implemented, so I kept my trap shut about it.)
