### ISSUE TITLE
Script error, "D4D.pk3:zd4d/powerups.txt"

### ISSUE THREAD

**Issue by ElonSatoshi** [MajorCooke/Doom4Doom#13]
This is D4D bleeding edge on GZdoom 2.3.2 compiled and installed from the Arch User Repository

When I try to run it I get a fatal error:

`Script error, "D4D.pk3:zd4d/powerups.txt" line 32:
Unexpected ':'
Expecting ';' or ','

1 errors while parsing D4D.pk3:zd4d/rune/playersummoner.txt`

**Comment by MajorCooke** [comment]
You need to use a DRD team build.

**Comment by ElonSatoshi** [comment]
Can you link me to their git?

**Comment by MajorCooke** [comment]
https://github.com/coelckers/gzdoom

Or if you dont want to bother building:
http://devbuilds.drdteam.org/gzdoom/

**Comment by apollo11w** [comment]
It's in the Arch aur, `gzdoom-git`
Which version of gzdoom do I need, Doom4Doom seems to crash on the very latest version

**Comment by ElonSatoshi** [comment]
Which version should I `git checkout`? Do I need version 2.5? It seems version 2.4 isn't working either.

**Comment by MajorCooke** [comment]
Make a new bug report please, I need to know the details.
