### ISSUE TITLE
zmenu.txt not compatible with test build of gzdoom.

### ISSUE THREAD

**Issue by ppsspp-gamer** [MajorCooke/Doom4Doom#14]
error log:

> D4D.pk3:zmenu.txt, line 15: Parent class Class of OptionMenuItemCvarDisplayInt not accessible to ZScript version 2.3.0
> D4D.pk3:zmenu.txt, line 62: Parent class Class of OptionMenuItemCreditDisplay not accessible to ZScript version 2.3.0
> D4D.pk3:zmenu.txt, line 111: Parent class Class of OptionMenuItemCostDisplay not accessible to ZScript version 2.3.0
> D4D.pk3:zmenu.txt, line 17: Type OptionMenuItemCvarDisplayInt not accessible to ZScript version 2.3.0
> D4D.pk3:zmenu.txt, line 66: Type OptionMenuItemCreditDisplay not accessible to ZScript version 2.3.0
> D4D.pk3:zmenu.txt, line 113: Type OptionMenuItemCostDisplay not accessible to ZScript version 2.3.0

**Comment by jewalky** [comment]
Don't use the latest devbuild. The versioning system is still incomplete.

**Comment by ppsspp-gamer** [comment]
@jewalky thanks for the hint, but which devbuild should I use?

**Comment by jewalky** [comment]
Like 2-3 days ago or so. Perhaps 5 days ago. Although now that versioning is declared official, it might be added to D4D as well.

**Comment by MajorCooke** [comment]
Be warned, menus are changing yet again. They already have in fact just recently as of this posting.

**Comment by MajorCooke** [comment]
Nevermind, they work fine.
