### ISSUE TITLE
Oversized completion rune-things, and pistol charge too large and offset.

### ISSUE THREAD

**Issue by ReilerTheDragonknight** [MajorCooke/Doom4Doom#15]
I have this problem with D4D where some HUD elements are way too large, like the completion runes. Any charging-thing if really large and offset from the cursor to the bottom right. I even tried getting a new build, didn't do jack shit. Help.

**Comment by MajorCooke** [comment]
Check your load order.

**Comment by ReilerTheDragonknight** [comment]
Sorry for being late with the response, Loading Resources first and Data last seemed to work wonders. Thanks.
