### ISSUE TITLE
Mod Crash?

### ISSUE THREAD

**Issue by Juggalage** [MajorCooke/Doom4Doom#20]
Every time I try to start up the mod (I downloaded the Master File and drag the .zip file onto a 3.1.0 version of GZDOOM) the game crashes and reads
"
Script error, "Doom4Doom-master.zip:zd4d/doom4player.txt" line 987:
Unknown identifier 'Shader'
Script error, "Doom4Doom-master.zip:zd4d/doom4player.txt" line 988:
Unknown identifier 'Shader'
Script error, "Doom4Doom-master.zip:zd4d/weapons/akimbofunctions.txt" line 208:
Unknown identifier 'PSPF_MIRROR'
Script error, "Doom4Doom-master.zip:zd4d/weapons/akimbofunctions.txt" line 1393:
Unknown identifier 'PSPF_MIRROR'

Execution could not continue.

4 errors while parsing DECORATE scripts
"
Is there any way I can fix this? Or is it on the devs side?

**Comment by MajorCooke** [comment]
Update your GZDoom to 3.2.x official.

**Comment by MajorCooke** [comment]
Since I haven't heard back on this issue, I'm closing this.
