### ISSUE TITLE
Enemies drop D4D weapons but weapons found on levels are Doom weapons

### ISSUE THREAD

**Issue by needo2** [MajorCooke/Doom4Doom#21]
When I pick a weapon spawned in the level I get the Doom variant. I can't switch back to these weapons after switching to another weapon.

For example I have D4D shotgun, I pick the double barrel on the second level and get Doom double barrel and it is in my hand, I switch back to D4D shotgun, I press next weapon key and I hear an error sound, I press it again I get to the fist weapon

**Comment by MajorCooke** [comment]
Are you using the next/previous weapon switching keybinds?

**Comment by MajorCooke** [comment]
Don't use the next/previous weapon switch keys right now, because they're trying to switch over to the akimbo weapon system. I'll be inventing a new set of keybinds for those so they can ignore the akimbo system safely when I next get time.

**Comment by needo2** [comment]
But weapons found on the levels should still give D4D weapons

**Comment by MajorCooke** [comment]
They do. Are you running any other mods on it? I just got done playing through Hell Revealed and everything works fine for me.

**Comment by needo2** [comment]
Apparently I am, I load mods through .bat files which runs a centeral .bat file which also imports   pk_anim1.wad from https://forum.zdoom.org/viewtopic.php?t=32628 along with the mod.
Never seen it broke another rom or previous versions of D4D I downloaded moddb so I completely forgot about it. Bug goes away when I remove it.

**Comment by MajorCooke** [comment]
If you're playing the alpha you also need to remove D4DResources.pk3, as it auto loads now if it's in the same directory as D4D.pk3 or Doom4Doom-master.zip.

**Comment by MajorCooke** [comment]
Any updates on this?

**Comment by MajorCooke** [comment]
Due to lack of response, this issue is closed.
