### ISSUE TITLE
Akimbo still needs work...

### ISSUE THREAD

**Issue by LeoNatan** [MajorCooke/Doom4Doom#23]
![screenshot_doom_20171216_061941](https://user-images.githubusercontent.com/2270433/34067267-7f07d82e-e229-11e7-9baa-a21e7451a9af.png)

😂

Either some weapons need to be disabled for akimbo, or the sprites need to be reworked so that they look more ... plausible.

One funny anecdote is the Doom VFR, where weapons somehow reload themselves. It's hilariously bad there too.

**Comment by MajorCooke** [comment]
None of them will be disabled. The plan is to import the D4T sprites and remove the hands from there, but in the event it does not happen, they will just remain as is.
