### ISSUE TITLE
[Git] Save Failed

### ISSUE THREAD

**Issue by Gehrich** [MajorCooke/Doom4Doom#25]
Using current commit (Jan 18, 2018) and GZDoom v3.2.4 and v3.2.5. Issue prevents saving and persists even with no other mods loaded and with a clean config.ini.

Console message:
Save Failed
Attempt to save pointer to unhandled type NativeStruct -CVar-

Edit: Saving possible in previous commit (Jan 10, 2018).

**Comment by MajorCooke** [comment]
Fixed.
