### ISSUE TITLE
BFG ammo bar doesn't fill correctly in HUD when additional ammo upgrade is in effect

### ISSUE THREAD

**Issue by BlueJayofEvil** [MajorCooke/Doom4Doom#29]
The green fill bar for the BFG ammo is fine when the default 3 ammo limit is present, but doesn't fill correctly when the additional ammo upgrade option is being used. Screenshots below.
I have only tested this in GZDoom (latest stable and git builds), not Zandronum or any other source ports.
![d4dbfg-3ammo](https://user-images.githubusercontent.com/1016034/45603000-f0e8a900-b9ec-11e8-9eb0-1cb14158c0c1.png)
![d4dbfg-4ammo](https://user-images.githubusercontent.com/1016034/45603001-f0e8a900-b9ec-11e8-98f9-5becfeb32cff.png)

**Comment by MajorCooke** [comment]
What is your screen resolution?

**Comment by MajorCooke** [comment]
https://puu.sh/Bwe32/56c144b03f.png
Works fine for me.

**Comment by BlueJayofEvil** [comment]
My resolution is 1366x768. I'll try different scaling options and see if that fixes it.

**Comment by MajorCooke** [comment]
Why are you giving me this? All I need to know from you is if it's misbehaving at a different resolution or not.

**Comment by BlueJayofEvil** [comment]
I've tried different resolutions as well as scaling options, to no avail. My default is 1366x768, but no other modes seem to fix the issue.
I figured maybe there's some setting in my config that might be a "red flag" known to cause issues?
I'm going to keep trying and testing to see if I can find a way to fix this on my end. If there's something specific you think might be the culprit, let me know and I'll try to see if it fixes it.

**Comment by MajorCooke** [comment]
Yeah, something is wrong here. I don't know what to tell you but keep messing with it. In the mean time I'm going to try and just see if I can hack up drawing them all independently instead of as a bar but chances are it'll probably make it worse.

**Comment by BlueJayofEvil** [comment]
Just tried it. Confirmed as fixed. Thanks!
