### ISSUE TITLE
Using the `Melee Attack` with LG leaves LG marks on walls

### ISSUE THREAD

**Issue by Reaper9** [MajorCooke/Doom4Doom#37]
When you stand next to a wall and use `Melee Attack` while the Lightning Gun is equipped, the punches leave Lightning Gun marks on walls (like [this](https://i.imgur.com/HnNNv6x.jpg)).

Tested with GZDoom v3.5.1 and the latest D4D from GitHub.

**Comment by MajorCooke** [comment]
Engine limitation I'm afraid.
