### ISSUE TITLE
The lightning effect stays after the ammo is depleted with a lightning gun

### ISSUE THREAD

**Issue by Reaper9** [MajorCooke/Doom4Doom#38]
Whenever you fully deplete the plasma ammo with a lightning gun, the lightning effect stays on the screen. This effect lasts until you get some plasma ammo and fire the lightning gun again or exit the level.

![This screenshot illustrates the issue.](https://user-images.githubusercontent.com/10687142/45919594-64346400-bea0-11e8-9f19-e28e8a4dd7a2.png)

**Comment by MajorCooke** [comment]
Fixed.
