### ISSUE TITLE
Ledge grabbing sometimes results in getting stuck in a wall

### ISSUE THREAD

**Issue by Reaper9** [MajorCooke/Doom4Doom#39]
What the title says. I have only experienced this issue in 2 places in one custom wad so far.

The issue shows itself in [this wad](https://www.doomworld.com/idgames/levels/doom2/megawads/abyss24a), the saves are [here](https://drive.google.com/file/d/16sDYHAbl1xOejisSkKvfsB2ukAgBDGNj/view?usp=sharing) and [here](https://drive.google.com/file/d/1qU8c4q2FZsi9ZL3n2B1isD5Hg4byYm0p/view?usp=sharing) (GZDoom v3.5.1).

[This video illustrates the issue.](https://drive.google.com/file/d/1StDaiie4Um9FaYmATWGqW_MLKll9r4xG/view?usp=sharing)

**Comment by MajorCooke** [comment]
I'm well aware this issue is present but for now, I'm contemplating outright disabling it.

**Comment by MajorCooke** [comment]
Finally addressed it. Hopefully its fixed now.
