### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by PopeRigby** [MajorCooke/Doom4Doom#55]
Is there a license for this repository?

**Comment by MajorCooke** [comment]
Not really, but I don't think one is needed. As stated in the readme (located in Docs folder), you're free to make modifications of your own and do as you please, so long as credit is given.

**Comment by postables** [comment]
Unlicensed code doesn't allow you to do that. Unlicensed code quite literally means you have rights to modify it, or do anything with it. 

Your statement `youre free to make modifications if your own and do as you please, so long as credit is given` == MIT license.

https://expressionengine.com/blog/the-truth-about-the-risks-of-unlicensed-software

**Comment by MajorCooke** [comment]
Not too happy about the "selling" clause, but nothing I can do about that... Oh well.

**Comment by PopeRigby** [comment]
You could do GPL, if you don't like the selling clause. That makes it so anyone who uses the code also has to make it open source. That would prevent someone from making a proprietary fork and profiting off of it.

**Comment by PopeRigby** [comment]
You can use the [GPL license](https://en.m.wikipedia.org/wiki/GNU_General_Public_License) if you're worried about somebody making a proprietary fork and selling it. The GPL prevents people from making closed source derivatives of your code.

**Comment by MajorCooke** [comment]
This mod isn't compatible with that because, if I'm reading it right, we need to have 100% of our own source material. I mean, we ARE using sounds straight from Doom 2016 itself, and other places. So I don't think it'd be a good idea to use it.

Also, if you want to discuss this further, please join our Discord server if you haven't already.
