### ISSUE TITLE
GZDoom error

### ISSUE THREAD

**Issue by Kizoky** [MajorCooke/Doom4Doom#57]
Branch: master
Tested with GZDoom 4.2.0 and latest devbuild

```
Script error, ":animdefs.aed" line 3:
Unknown texture UAC_ROT0
```

**Comment by MajorCooke** [comment]
If you're using the github version, download https://github.com/MajorCooke/Doom4DoomResources this variant with it. I'll fix this in the instructions.

**Comment by MajorCooke** [comment]
I've updated the [instructions](https://docs.google.com/document/d/1Z52m_OvyBmmNi1yERhQPd88fLe91LYd0LrN36OId5BA/edit?usp=sharing) to indicate that bleeding should be used for right now since the installation instructions changed from the prior version to the latest stable.
