### ISSUE TITLE
41 errors, 0 warnings while compiling :zscript.txt

### ISSUE THREAD

**Issue by zZSKz** [MajorCooke/Doom4Doom#59]
:zd4d/doom4player.txt, line 33: Unable to resolve MCHandler as type.
:zd4d/upgrades.txt, line 792: Unable to resolve MC_Quaternion as type.
:zd4d/weapons/grenades.txt, line 302: Unable to resolve MCHandler as type.
:zd4d/weapons/grenades.txt, line 776: Unable to resolve MCHandler as type.
:zd4d/weapons/grenades.txt, line 971: Unable to resolve MCHandler as type.
:zd4d/weapons/baseweapon.txt, line 18: Unable to resolve MCHandler as type.
:zd4d/weapons/rocketlauncher.txt, line 19: Unable to resolve MCHudShape as type.
:zd4d/weapons/bfg.txt, line 260: Unable to resolve MCHandler as type.
:zd4d/monsters/monsterbase.txt, line 32: Unable to resolve MCHandler as type.
:zd4d/event.txt, line 46: Unable to resolve MCHandler as type.
:zd4d/doom4player.txt, line 33: Unable to resolve MCHandler as type.
:zd4d/upgrades.txt, line 792: Unable to resolve MC_Quaternion as type.
:zd4d/weapons/grenades.txt, line 302: Unable to resolve MCHandler as type.
:zd4d/weapons/grenades.txt, line 776: Unable to resolve MCHandler as type.
:zd4d/weapons/grenades.txt, line 971: Unable to resolve MCHandler as type.
:zd4d/weapons/baseweapon.txt, line 18: Unable to resolve MCHandler as type.
:zd4d/weapons/rocketlauncher.txt, line 19: Unable to resolve MCHudShape as type.
:zd4d/weapons/bfg.txt, line 260: Unable to resolve MCHandler as type.
:zd4d/monsters/monsterbase.txt, line 32: Unable to resolve MCHandler as type.
:zd4d/event.txt, line 46: Unable to resolve MCHandler as type.
:zd4d/doom4player.txt, line 5: Unable to resolve all fields for class Doom4Player
:zd4d/upgrades.txt, line 790: Unable to resolve all fields for class D4UpgradeDrone
:zd4d/weapons/grenades.txt, line 300: Unable to resolve all fields for class D4SyphonGrenade
:zd4d/weapons/grenades.txt, line 773: Unable to resolve all fields for class D4PlayerHolograph
:zd4d/weapons/grenades.txt, line 966: Unable to resolve all fields for class D4FlamePoint
:zd4d/weapons/baseweapon.txt, line 11: Unable to resolve all fields for class Doom4Weapon
:zd4d/weapons/rocketlauncher.txt, line 16: Unable to resolve all fields for class D4RocketLauncher
:zd4d/weapons/bfg.txt, line 255: Unable to resolve all fields for class D4BFGProjectile
:zd4d/monsters/monsterbase.txt, line 23: Unable to resolve all fields for class D4AbstractMonster
:zd4d/event.txt, line 41: Unable to resolve all fields for class D4DHandler
:zd4d/doom4player.txt, line 69: Variable UseLives not found in Doom4Player
:zd4d/weapons/baseweapon.txt, line 23: Variable MultiplayerWeapon not found in Doom4Weapon
:zd4d/monsters/monsterbase.txt, line 49: Variable UpgradeDropChance not found in D4AbstractMonster
:zd4d/monsters/monsterbase.txt, line 50: Variable UpgradeDropAlways not found in D4AbstractMonster
:zd4d/monsters/monsterbase.txt, line 51: Variable CrateDropChance not found in D4AbstractMonster
:zd4d/monsters/monsterbase.txt, line 52: Variable CrateDropAmount not found in D4AbstractMonster
:zd4d/monsters/monsterbase.txt, line 53: Variable CrateDropAlways not found in D4AbstractMonster
:zd4d/monsters/monsterbase.txt, line 54: Variable CashAmount not found in D4AbstractMonster
:zd4d/monsters/monsterbase.txt, line 55: Variable CashChainsawPinata not found in D4AbstractMonster
:zd4d/beambase.txt, line 554: Unable to resolve MC_Quaternion as type.
:zd4d/upgrades.txt, line 845: Unable to resolve MC_Quaternion as type.

Execution could not continue.

41 errors, 0 warnings while compiling :zscript.txt

i get this everytime i try to open the mod
i'm using GZDoom g4.2.1 64bits

**Comment by MajorCooke** [comment]
You forgot to include MC_Utility. [Here's the installation instructions.](https://docs.google.com/document/d/1Z52m_OvyBmmNi1yERhQPd88fLe91LYd0LrN36OId5BA/edit?usp=sharing)
