### ISSUE TITLE
Crash with Oblige generated boss arenas.

### ISSUE THREAD

**Issue by magpie514** [MajorCooke/Doom4Doom#61]
When entering boss arenas generated by Oblige, the VM execution is aborted by a null read (tried to read from address zero).
Two instances of this happen in the code. 
* line 212 of Doom4Doom-master.zip:zd4d/event.txt
* line 302 of MC_Utility-master.zip:mc/base.txt.

Please add null checks for `mo` pointer at lines 211 and 300 respectively. ( `if (mo == null) { return; }`) , that seems enough to fix.

**Comment by MajorCooke** [comment]
Done.
