### ISSUE TITLE
Possible feature suggestion

### ISSUE THREAD

**Issue by Dudejo** [MajorCooke/Doom4Doom#63]
Hi.

In spite of a few hiccups, I like what you guys have done with this mod. It's pretty brutal on Nightmare but I made it to the end of Knee-Deep.

I have a suggestion, mostly from a Doom 1 perspective. Would it be feasible to make backpacks provide a free upgrade? Or a large stack of upgrade credits? Given the episodic nature of the game, you're already past a good chunk of levels before getting to the good stuff.

Ammo upgrades could simply be moved to the upgrade menu like everything else?

**Comment by MajorCooke** [comment]
Unfortunately, development for this mod is going to cease soon in favor of moving to DE4D completely. As such this mod will no longer be maintained, so there are no large scale changes in the works for D4D anymore. 

Sorry to disappoint, but I'm pretty much ready to be done with this mod as I want to move onto demaking Doom Eternal.
