### ISSUE TITLE
[Git] Fatal Error on startup

### ISSUE THREAD

**Issue by Techokami** [MajorCooke/Doom4Doom#8]
Doom4Doom commit 8dcdb5c, Doom4DoomResources commit 300c9a2, GZDoom 2.3.1
I took the contents of the repos, crunched them together as a ZIP with a PK3 extension, loaded it into GZDoom, and [this is the console log.](http://pastebin.com/bpptr0Dp)

(I know I should be using command line parameters to set up a shortcut that uses directories and have them point to local copies of the Git repos instead of manually building PK3s every time I want to test a new Git version, but ![:effort:](http://junks.holenet.info/SA_emotes/emot-effort.gif))

**Comment by NVICE** [comment]
You need to update to GZDoom 2.3.2 ;)

**Comment by Techokami** [comment]
I just updated to 2.3.2, same error.

**Comment by NVICE** [comment]
In that case, try one one of the recent builds at:
http://devbuilds.drdteam.org/gzdoom/
I believe anything past Jan 10 should work.

**Comment by Techokami** [comment]
NOW it works. Thanks!
