### ISSUE TITLE
[Git] Music system can be killed

### ISSUE THREAD

**Issue by Techokami** [MajorCooke/Doom4Doom#9]
Doom4Doom commit 8dcdb5c, Doom4DoomResources commit 300c9a2, GZDoom 2.4pre-127-g386c00f
Playing Doom II's MAP02, got the Completionist Bonus at the end of the map. While the jingle was playing, I opened up the Upgrades menu and bought the first tier of Credits upgrade for the suit. Then I closed the Upgrades menu and immediately hit the Exit switch.
This caused all music to stop playing. Nothing on the intermission screen, nothing in MAP03.

**Comment by MajorCooke** [comment]
Should be fixed now.
